//*
// Copyright 2023 buexplain@qq.com
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: connOpenCustomUniqIdTokenReq.proto

package netsvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// business向worker请求，设置连接打开时，传递自定义uniqId时的校验token
type ConnOpenCustomUniqIdTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// token，随机性很强的字符串
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 网关在延时多少秒后删除token
	Delay int32 `protobuf:"varint,2,opt,name=delay,proto3" json:"delay,omitempty"`
}

func (x *ConnOpenCustomUniqIdTokenReq) Reset() {
	*x = ConnOpenCustomUniqIdTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connOpenCustomUniqIdTokenReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnOpenCustomUniqIdTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnOpenCustomUniqIdTokenReq) ProtoMessage() {}

func (x *ConnOpenCustomUniqIdTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_connOpenCustomUniqIdTokenReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnOpenCustomUniqIdTokenReq.ProtoReflect.Descriptor instead.
func (*ConnOpenCustomUniqIdTokenReq) Descriptor() ([]byte, []int) {
	return file_connOpenCustomUniqIdTokenReq_proto_rawDescGZIP(), []int{0}
}

func (x *ConnOpenCustomUniqIdTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConnOpenCustomUniqIdTokenReq) GetDelay() int32 {
	if x != nil {
		return x.Delay
	}
	return 0
}

var File_connOpenCustomUniqIdTokenReq_proto protoreflect.FileDescriptor

var file_connOpenCustomUniqIdTokenReq_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x6f, 0x6e, 0x6e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x55, 0x6e, 0x69, 0x71, 0x49, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x6e, 0x65, 0x74, 0x73, 0x76, 0x72, 0x2e, 0x63, 0x6f, 0x6e,
	0x6e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x55, 0x6e, 0x69, 0x71, 0x49,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x22, 0x4a, 0x0a, 0x1c, 0x43, 0x6f, 0x6e,
	0x6e, 0x4f, 0x70, 0x65, 0x6e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x55, 0x6e, 0x69, 0x71, 0x49,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x42, 0x27, 0x5a, 0x07, 0x6e, 0x65, 0x74, 0x73, 0x76, 0x72, 0x2f,
	0xca, 0x02, 0x06, 0x4e, 0x65, 0x74, 0x73, 0x76, 0x72, 0xe2, 0x02, 0x12, 0x4e, 0x65, 0x74, 0x73,
	0x76, 0x72, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connOpenCustomUniqIdTokenReq_proto_rawDescOnce sync.Once
	file_connOpenCustomUniqIdTokenReq_proto_rawDescData = file_connOpenCustomUniqIdTokenReq_proto_rawDesc
)

func file_connOpenCustomUniqIdTokenReq_proto_rawDescGZIP() []byte {
	file_connOpenCustomUniqIdTokenReq_proto_rawDescOnce.Do(func() {
		file_connOpenCustomUniqIdTokenReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_connOpenCustomUniqIdTokenReq_proto_rawDescData)
	})
	return file_connOpenCustomUniqIdTokenReq_proto_rawDescData
}

var file_connOpenCustomUniqIdTokenReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_connOpenCustomUniqIdTokenReq_proto_goTypes = []interface{}{
	(*ConnOpenCustomUniqIdTokenReq)(nil), // 0: netsvr.connOpenCustomUniqIdTokenReq.ConnOpenCustomUniqIdTokenReq
}
var file_connOpenCustomUniqIdTokenReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_connOpenCustomUniqIdTokenReq_proto_init() }
func file_connOpenCustomUniqIdTokenReq_proto_init() {
	if File_connOpenCustomUniqIdTokenReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connOpenCustomUniqIdTokenReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnOpenCustomUniqIdTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connOpenCustomUniqIdTokenReq_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connOpenCustomUniqIdTokenReq_proto_goTypes,
		DependencyIndexes: file_connOpenCustomUniqIdTokenReq_proto_depIdxs,
		MessageInfos:      file_connOpenCustomUniqIdTokenReq_proto_msgTypes,
	}.Build()
	File_connOpenCustomUniqIdTokenReq_proto = out.File
	file_connOpenCustomUniqIdTokenReq_proto_rawDesc = nil
	file_connOpenCustomUniqIdTokenReq_proto_goTypes = nil
	file_connOpenCustomUniqIdTokenReq_proto_depIdxs = nil
}
